name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "✨ Features"
    labels:
      - feature
      - enhancement
      - new-feature
      - feat
  - title: "🐞 Bug Fixes"
    labels:
      - fix
      - bugfix
      - bug
      - defect
  - title: "📄 Other Changes"
    labels:
      - other
      - documentation
      - docs
  - title: "🔧 Maintenance"
    labels:
      - chore
      - refactor
      - maintenance

change-template: '- $TITLE by @$AUTHOR (#$NUMBER): $BODY'

version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - feature
      - feat
      - enhancement
  patch:
    labels:
      - patch
      - fix
      - bug
      - chore
      - maintenance
  default: patch

template: |
  ## 🚀 Release Notes for v$RESOLVED_VERSION

  {{#categories}}
  ## {{title}}
  {{#pullRequests}}
  - $TITLE by @$AUTHOR (#$NUMBER): $BODY
  {{/pullRequests}}
  {{/categories}}

  ## 🏅 Contributors
  {{#contributors}}
  - @$USERNAME
  {{/contributors}}
